// Copyright 2026 Christopher Collins
//
// Licensed under the MIT License. See LICENSE in the project root for details.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *GitOpsWatcher) DeepCopyInto(out *GitOpsWatcher) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of this GitOpsWatcher.
func (in *GitOpsWatcher) DeepCopy() *GitOpsWatcher {
	if in == nil {
		return nil
	}
	out := new(GitOpsWatcher)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *GitOpsWatcher) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another GitOpsWatcherList.
func (in *GitOpsWatcherList) DeepCopyInto(out *GitOpsWatcherList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GitOpsWatcher, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of this GitOpsWatcherList.
func (in *GitOpsWatcherList) DeepCopy() *GitOpsWatcherList {
	if in == nil {
		return nil
	}
	out := new(GitOpsWatcherList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *GitOpsWatcherList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this GitOpsWatcherSpec.
func (in *GitOpsWatcherSpec) DeepCopyInto(out *GitOpsWatcherSpec) {
	*out = *in
	if in.DocsPaths != nil {
		in, out := &in.DocsPaths, &out.DocsPaths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ReconcileTimeout != nil {
		in, out := &in.ReconcileTimeout, &out.ReconcileTimeout
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy returns a deep copy of this GitOpsWatcherSpec.
func (in *GitOpsWatcherSpec) DeepCopy() *GitOpsWatcherSpec {
	if in == nil {
		return nil
	}
	out := new(GitOpsWatcherSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this GitOpsWatcherStatus.
func (in *GitOpsWatcherStatus) DeepCopyInto(out *GitOpsWatcherStatus) {
	*out = *in
	if in.LastReconcileTime != nil {
		in, out := &in.LastReconcileTime, &out.LastReconcileTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of this GitOpsWatcherStatus.
func (in *GitOpsWatcherStatus) DeepCopy() *GitOpsWatcherStatus {
	if in == nil {
		return nil
	}
	out := new(GitOpsWatcherStatus)
	in.DeepCopyInto(out)
	return out
}
